import = [
  "~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

